export const GET_POSTS_REQUEST: 'GET_POSTS_REQUEST' = 'GET_POSTS_REQUEST';
export const GET_POSTS_FAILED: 'GET_POSTS_FAILED' = 'GET_POSTS_FAILED';
export const GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS' = 'GET_POSTS_SUCCESS';

export const ADD_POST_MODAL: 'ADD_POST_MODAL' = 'ADD_POST_MODAL';

export const CLEAR_COMMENTS: 'CLEAR_COMMENTS' = 'CLEAR_COMMENTS';

export const GET_COMMENTS_REQUEST: 'GET_COMMENTS_REQUEST' = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_FAILED: 'GET_COMMENTS_FAILED' = 'GET_COMMENTS_FAILED';
export const GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS' = 'GET_COMMENTS_SUCCESS';

export const MORE_POSTS_REQUEST: 'MORE_POSTS_REQUEST' = 'MORE_POSTS_REQUEST';
export const MORE_POSTS_FAILED: 'MORE_POSTS_REQUEST' = 'MORE_POSTS_REQUEST';
export const MORE_POSTS_SUCCESS: 'MORE_POSTS_SUCCESS' = 'MORE_POSTS_SUCCESS';

export const POST_CARMA_UP: 'POST_CARMA_UP' = 'POST_CARMA_UP';
export const POST_CARMA_DOWN: 'POST_CARMA_DOWN' = 'POST_CARMA_DOWN';

export const COMMENT_CARMA_UP: 'COMMENT_CARMA_UP' = 'COMMENT_CARMA_UP';
export const COMMENT_CARMA_DOWN: 'COMMENT_CARMA_DOWN' = 'COMMENT_CARMA_DOWN';

export const CHANGE_CARMA: 'CHANGE_CARMA' = 'CHANGE_CARMA';